/**
 * Agent Event Zod Schemas
 *
 * Single source of truth for agent event types.
 * Per DYK-03: Zod schemas in shared, derive TS types via z.infer<>
 *
 * These schemas define:
 * - tool_call: Agent invoking a tool (Bash, Read, Write, etc.)
 * - tool_result: Result of tool execution (output, success/error)
 * - thinking: Agent reasoning/thinking blocks (Claude extended thinking, Copilot reasoning)
 *
 * Part of Plan 015: Agent Activity Fidelity Enhancement (Phase 1)
 */
import { z } from 'zod';

// ============ Base Event Structure ============

/**
 * Base schema for all agent events.
 * Includes timestamp for ordering and optional event ID for storage.
 */
export const AgentEventBaseSchema = z.object({
  /** Event timestamp (ISO 8601) */
  timestamp: z.string().datetime(),
  /** Event ID (generated by storage service) */
  id: z.string().optional(),
});

// ============ Tool Call Event ============

/**
 * Schema for tool_call events.
 * Emitted when an agent invokes a tool (Bash, Read, Write, etc.).
 *
 * Per spec AC1: UI displays tool card within 500ms of execution start.
 */
export const AgentToolCallEventSchema = AgentEventBaseSchema.extend({
  type: z.literal('tool_call'),
  data: z.object({
    /** Name of the tool being invoked (e.g., 'Bash', 'Read', 'Write') */
    toolName: z.string(),
    /** Tool input parameters (shape varies by tool) */
    input: z.unknown(),
    /** Unique identifier linking to corresponding tool_result */
    toolCallId: z.string(),
  }),
});

// ============ Tool Result Event ============

/**
 * Schema for tool_result events.
 * Emitted when a tool execution completes.
 *
 * Per spec AC2: UI updates tool card to show success/error status and output.
 * Per spec AC12a: Tool cards auto-expand when error occurs.
 */
export const AgentToolResultEventSchema = AgentEventBaseSchema.extend({
  type: z.literal('tool_result'),
  data: z.object({
    /** Links to originating tool_call event */
    toolCallId: z.string(),
    /** Tool execution output (stdout/result) */
    output: z.string(),
    /** True if tool execution failed */
    isError: z.boolean(),
  }),
});

// ============ Thinking Event ============

/**
 * Schema for thinking events.
 * Emitted for Claude extended thinking or Copilot reasoning blocks.
 *
 * Per spec AC5: Thinking blocks appear as collapsible "Thinking..." sections.
 * Per spec AC6a: Displayed by default but collapsed.
 */
export const AgentThinkingEventSchema = AgentEventBaseSchema.extend({
  type: z.literal('thinking'),
  data: z.object({
    /** Thinking/reasoning content */
    content: z.string(),
    /** Cryptographic signature (Claude extended thinking only) */
    signature: z.string().optional(),
  }),
});

// ============ Message Event ============

/**
 * Schema for message events.
 * Final assistant message content (complete, not delta).
 *
 * For Claude: result message with accumulated content
 * For Copilot: assistant.message
 */
export const AgentMessageEventSchema = AgentEventBaseSchema.extend({
  type: z.literal('message'),
  data: z.object({
    /** Complete message content */
    content: z.string(),
    /** Message ID if available */
    messageId: z.string().optional(),
  }),
});

// ============ Type Exports (via z.infer) ============

/** TypeScript type derived from AgentToolCallEventSchema */
export type AgentToolCallEvent = z.infer<typeof AgentToolCallEventSchema>;

/** TypeScript type derived from AgentToolResultEventSchema */
export type AgentToolResultEvent = z.infer<typeof AgentToolResultEventSchema>;

/** TypeScript type derived from AgentThinkingEventSchema */
export type AgentThinkingEvent = z.infer<typeof AgentThinkingEventSchema>;

/** TypeScript type derived from AgentMessageEventSchema */
export type AgentMessageEvent = z.infer<typeof AgentMessageEventSchema>;

// ============ Union Schema for All New Event Types ============

/**
 * Union of all storable agent event schemas.
 * These are persisted to disk and can be retrieved via the events API.
 */
export const AgentStoredEventSchema = z.discriminatedUnion('type', [
  AgentToolCallEventSchema,
  AgentToolResultEventSchema,
  AgentThinkingEventSchema,
  AgentMessageEventSchema,
]);

/** Union type for all new agent events */
export type AgentStoredEvent = z.infer<typeof AgentStoredEventSchema>;

// ============ Schema Array for Extension ============

/**
 * Array of storable event schemas for extending existing unions.
 * Usage: Add to discriminated union in agent-types.ts or SSE schemas.
 */
export const agentStoredEventSchemas = [
  AgentToolCallEventSchema,
  AgentToolResultEventSchema,
  AgentThinkingEventSchema,
  AgentMessageEventSchema,
] as const;
