#!/usr/bin/env node
/**
 * Harness CLI entry point.
 *
 * Agents invoke: `harness <command> [options]`
 * All commands return a HarnessEnvelope JSON to stdout.
 *
 * On every invocation, regenerates harness/.env from computePorts()
 * so that direct `docker compose` commands also use the correct ports.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { Command } from 'commander';
import { computePorts } from '../ports/allocator.js';
import { registerBuildCommand } from './commands/build.js';
import { registerDevCommand } from './commands/dev.js';
import { registerStopCommand } from './commands/stop.js';
import { registerHealthCommand } from './commands/health.js';
import { registerTestCommand } from './commands/test.js';
import { registerScreenshotCommand } from './commands/screenshot.js';
import { registerResultsCommand } from './commands/results.js';
import { registerPortsCommand } from './commands/ports.js';
import { registerSeedCommand } from './commands/seed.js';
import { registerDoctorCommand } from './commands/doctor.js';

const HARNESS_ROOT = path.resolve(import.meta.dirname ?? '.', '../..');

function syncEnvFile(): void {
  const ports = computePorts();
  const content = [
    `# Auto-generated by harness CLI — do not edit`,
    `# Worktree: ${ports.worktree} (slot ${ports.slot})`,
    `HARNESS_APP_PORT=${ports.app}`,
    `HARNESS_TERMINAL_PORT=${ports.terminal}`,
    `HARNESS_CDP_PORT=${ports.cdp}`,
    `HARNESS_WORKTREE=${ports.worktree}`,
    '',
  ].join('\n');

  const envPath = path.join(HARNESS_ROOT, '.env');
  // Only write if changed to avoid unnecessary disk writes
  if (existsSync(envPath)) {
    const existing = readFileSync(envPath, 'utf-8');
    if (existing === content) return;
  }
  writeFileSync(envPath, content);
}

export function createCli(): Command {
  const program = new Command()
    .name('harness')
    .version('0.1.0')
    .description('Agentic development harness for Chainglass');

  registerBuildCommand(program);
  registerDevCommand(program);
  registerStopCommand(program);
  registerHealthCommand(program);
  registerTestCommand(program);
  registerScreenshotCommand(program);
  registerResultsCommand(program);
  registerPortsCommand(program);
  registerSeedCommand(program);
  registerDoctorCommand(program);

  return program;
}

// Run if executed directly (not imported for testing)
const isDirectRun = process.argv[1]?.endsWith('index.ts') || process.argv[1]?.endsWith('index.js');
if (isDirectRun) {
  syncEnvFile();
  const program = createCli();
  program.parseAsync(process.argv);
}
