import { describe, expect, it, beforeEach } from 'vitest';

import type { ProcessSignal } from '@chainglass/shared';
import { FakeProcessManager } from '@chainglass/shared';

describe('FakeProcessManager', () => {
  let manager: FakeProcessManager;

  beforeEach(() => {
    manager = new FakeProcessManager();
  });

  describe('spawn() behavior', () => {
    it('should return a ProcessHandle with pid on spawn()', async () => {
      /*
      Test Doc:
      - Why: spawn() must return valid handle for process tracking
      - Contract: spawn() returns ProcessHandle with positive pid
      - Usage Notes: PID is auto-generated by fake for uniqueness
      - Quality Contribution: Ensures spawn returns usable handle
      - Worked Example: spawn({command:'node'}) → {pid: 1001, ...}
      */
      const handle = await manager.spawn({
        command: 'echo',
        args: ['test'],
      });

      expect(handle).toBeDefined();
      expect(handle.pid).toBeDefined();
      expect(handle.pid).toBeGreaterThan(0);
    });

    it('should increment pid for each spawn', async () => {
      /*
      Test Doc:
      - Why: Each spawned process needs unique PID
      - Contract: Consecutive spawns have incrementing PIDs
      - Usage Notes: Fake starts from base PID and increments
      - Quality Contribution: Enables tracking multiple processes
      - Worked Example: spawn(), spawn() → PIDs 1001, 1002
      */
      const handle1 = await manager.spawn({ command: 'echo' });
      const handle2 = await manager.spawn({ command: 'echo' });

      expect(handle2.pid).toBeGreaterThan(handle1.pid);
    });

    it('should record spawn calls in history', async () => {
      /*
      Test Doc:
      - Why: Tests may need to verify what processes were spawned
      - Contract: getSpawnHistory() returns all spawn options
      - Usage Notes: History preserved across calls
      - Quality Contribution: Enables spawn verification
      - Worked Example: spawn({command:'a'}), spawn({command:'b'}) → history has both
      */
      await manager.spawn({ command: 'echo', args: ['one'] });
      await manager.spawn({ command: 'node', args: ['--version'], cwd: '/tmp' });

      const history = manager.getSpawnHistory();
      expect(history).toHaveLength(2);
      expect(history[0].command).toBe('echo');
      expect(history[1].command).toBe('node');
      expect(history[1].cwd).toBe('/tmp');
    });
  });

  describe('signal tracking', () => {
    it('should record signals sent to process', async () => {
      /*
      Test Doc:
      - Why: Signal escalation tests need to verify signal sequence
      - Contract: getSignalsSent(pid) returns all signals sent to that PID
      - Usage Notes: Returns empty array if no signals sent
      - Quality Contribution: Enables signal escalation verification
      - Worked Example: signal(pid, 'SIGINT'), signal(pid, 'SIGTERM') → ['SIGINT','SIGTERM']
      */
      const handle = await manager.spawn({ command: 'sleep' });

      await manager.signal(handle.pid, 'SIGINT');
      await manager.signal(handle.pid, 'SIGTERM');
      await manager.signal(handle.pid, 'SIGKILL');

      const signals = manager.getSignalsSent(handle.pid);
      expect(signals).toEqual(['SIGINT', 'SIGTERM', 'SIGKILL']);
    });

    it('should record signal timing for escalation verification', async () => {
      /*
      Test Doc:
      - Why: AC-14 requires 2-second intervals between signals
      - Contract: getSignalTimings(pid) returns timestamps for each signal
      - Usage Notes: Times are approximate; test for >= expected interval
      - Quality Contribution: Enables timing verification
      - Worked Example: signal() at t=0, t=2000, t=4000 → timestamps match
      */
      const handle = await manager.spawn({ command: 'sleep' });

      await manager.signal(handle.pid, 'SIGINT');
      await new Promise((resolve) => setTimeout(resolve, 50));
      await manager.signal(handle.pid, 'SIGTERM');

      const timings = manager.getSignalTimings(handle.pid);
      expect(timings).toHaveLength(2);
      expect(timings[1]).toBeGreaterThan(timings[0]);
    });

    it('should return empty array for pid with no signals', async () => {
      /*
      Test Doc:
      - Why: Query for unknown PID should not throw
      - Contract: getSignalsSent() returns [] for PID with no signals
      - Usage Notes: Safe to call for any PID value
      - Quality Contribution: Prevents undefined errors
      - Worked Example: getSignalsSent(9999) → []
      */
      expect(manager.getSignalsSent(9999)).toEqual([]);
      expect(manager.getSignalTimings(9999)).toEqual([]);
    });
  });

  describe('terminate() behavior', () => {
    it('should perform signal escalation on terminate()', async () => {
      /*
      Test Doc:
      - Why: Per spec, terminate uses SIGINT → SIGTERM → SIGKILL
      - Contract: terminate(pid) sends escalating signals to stubborn process
      - Usage Notes: Default fake ignores signals until SIGKILL
      - Quality Contribution: Verifies full escalation sequence
      - Worked Example: terminate(stubborn-pid) → all 3 signals sent
      */
      // Create a stubborn process (ignores SIGINT/SIGTERM)
      const handle = await manager.spawn({ command: 'sleep' });
      manager.makeProcessStubborn(handle.pid);

      await manager.terminate(handle.pid);

      const signals = manager.getSignalsSent(handle.pid);
      expect(signals).toContain('SIGINT');
      expect(signals).toContain('SIGTERM');
      expect(signals).toContain('SIGKILL');
    });

    it('should stop escalation if process exits early', async () => {
      /*
      Test Doc:
      - Why: Don't send signals to already-exited process
      - Contract: terminate() stops when process exits, before SIGKILL if possible
      - Usage Notes: Process configured to exit on SIGTERM stops escalation
      - Quality Contribution: Verifies early exit handling
      - Worked Example: exit-on-sigterm process → only SIGINT, SIGTERM sent
      */
      const handle = await manager.spawn({ command: 'sleep' });
      manager.exitProcessOnSignal(handle.pid, 'SIGTERM');

      await manager.terminate(handle.pid);

      const signals = manager.getSignalsSent(handle.pid);
      expect(signals).toContain('SIGINT');
      expect(signals).toContain('SIGTERM');
      expect(signals).not.toContain('SIGKILL');
    });

    it('should mark process as not running after terminate()', async () => {
      /*
      Test Doc:
      - Why: After termination, isRunning should return false
      - Contract: terminate(pid) causes isRunning(pid) to return false
      - Usage Notes: Even if process was stubborn, terminate ensures exit
      - Quality Contribution: Verifies process state after termination
      - Worked Example: terminate(pid) → isRunning(pid) → false
      */
      const handle = await manager.spawn({ command: 'sleep' });
      expect(await manager.isRunning(handle.pid)).toBe(true);

      await manager.terminate(handle.pid);

      expect(await manager.isRunning(handle.pid)).toBe(false);
    });
  });

  describe('isRunning() and getPid()', () => {
    it('should report isRunning() true for spawned process', async () => {
      /*
      Test Doc:
      - Why: isRunning indicates current process state
      - Contract: isRunning(pid) returns true for active processes
      - Usage Notes: Fake manages internal running state
      - Quality Contribution: Enables process monitoring
      - Worked Example: spawn() → isRunning(pid) → true
      */
      const handle = await manager.spawn({ command: 'sleep' });

      expect(await manager.isRunning(handle.pid)).toBe(true);
    });

    it('should report isRunning() false for unknown pid', async () => {
      /*
      Test Doc:
      - Why: Unknown PIDs should report not running
      - Contract: isRunning() returns false for PIDs not spawned
      - Usage Notes: Does not throw for unknown PIDs
      - Quality Contribution: Safe querying behavior
      - Worked Example: isRunning(9999) → false
      */
      expect(await manager.isRunning(9999)).toBe(false);
    });

    it('should return pid from getPid()', async () => {
      /*
      Test Doc:
      - Why: Utility method for extracting PID from handle
      - Contract: getPid(handle) returns handle.pid
      - Usage Notes: Simple accessor for consistency
      - Quality Contribution: API completeness
      - Worked Example: getPid({pid: 123}) → 123
      */
      const handle = await manager.spawn({ command: 'echo' });

      expect(manager.getPid(handle)).toBe(handle.pid);
    });
  });

  describe('assertion helpers', () => {
    it('should assertSpawnCalled() pass when spawn() was called', async () => {
      /*
      Test Doc:
      - Why: Tests need to verify spawn was invoked
      - Contract: assertSpawnCalled(options) passes if matching call exists
      - Usage Notes: Partial matching on options
      - Quality Contribution: Simplifies spawn verification
      - Worked Example: spawn({command:'echo'}); assertSpawnCalled({command:'echo'}) → pass
      */
      await manager.spawn({ command: 'node', args: ['--version'] });

      expect(() => manager.assertSpawnCalled({ command: 'node' })).not.toThrow();
    });

    it('should assertSpawnCalled() throw when not called', () => {
      /*
      Test Doc:
      - Why: Assertion must fail when expected spawn didn't happen
      - Contract: assertSpawnCalled() throws if no match
      - Usage Notes: Error message includes actual history
      - Quality Contribution: Clear test failures
      - Worked Example: assertSpawnCalled({command:'x'}) with no calls → throw
      */
      expect(() => manager.assertSpawnCalled({ command: 'never' })).toThrow(
        /Expected spawn\(\) to be called with/
      );
    });

    it('should assertSignalSent() pass when signal was sent', async () => {
      /*
      Test Doc:
      - Why: Tests need to verify specific signals were sent
      - Contract: assertSignalSent(pid, signal) passes if signal was sent
      - Usage Notes: Must match both pid and signal type
      - Quality Contribution: Simplifies signal verification
      - Worked Example: signal(pid, 'SIGINT'); assertSignalSent(pid, 'SIGINT') → pass
      */
      const handle = await manager.spawn({ command: 'sleep' });
      await manager.signal(handle.pid, 'SIGTERM');

      expect(() => manager.assertSignalSent(handle.pid, 'SIGTERM')).not.toThrow();
    });

    it('should assertSignalSent() throw when signal not sent', async () => {
      /*
      Test Doc:
      - Why: Assertion must fail when expected signal wasn't sent
      - Contract: assertSignalSent() throws if signal not in history
      - Usage Notes: Error includes actual signals sent
      - Quality Contribution: Clear failure messages
      - Worked Example: assertSignalSent(pid, 'SIGKILL') when only SIGINT sent → throw
      */
      const handle = await manager.spawn({ command: 'sleep' });
      await manager.signal(handle.pid, 'SIGINT');

      expect(() => manager.assertSignalSent(handle.pid, 'SIGKILL')).toThrow(
        /Expected signal SIGKILL to be sent/
      );
    });
  });

  describe('waitForExit() behavior', () => {
    it('should waitForExit() resolve with exit code', async () => {
      /*
      Test Doc:
      - Why: Callers need to wait for process completion
      - Contract: handle.waitForExit() resolves with ProcessExitResult
      - Usage Notes: Blocks until process exits; may need timeout
      - Quality Contribution: Enables completion waiting
      - Worked Example: waitForExit() → {exitCode: 0}
      */
      const handle = await manager.spawn({ command: 'echo' });
      manager.exitProcess(handle.pid, 0);

      const result = await handle.waitForExit();

      expect(result.exitCode).toBe(0);
    });

    it('should return configured exit code', async () => {
      /*
      Test Doc:
      - Why: Different exit codes indicate success/failure
      - Contract: exitProcess(pid, code) causes waitForExit to return that code
      - Usage Notes: Code 0 = success, >0 = failure
      - Quality Contribution: Enables exit code testing
      - Worked Example: exitProcess(pid, 1) → waitForExit() → {exitCode: 1}
      */
      const handle = await manager.spawn({ command: 'fail' });
      manager.exitProcess(handle.pid, 1);

      const result = await handle.waitForExit();

      expect(result.exitCode).toBe(1);
    });
  });

  describe('reset functionality', () => {
    it('should clear all state on reset()', async () => {
      /*
      Test Doc:
      - Why: Tests need fresh state between test cases
      - Contract: reset() clears spawn history, signal history, running state
      - Usage Notes: Call in beforeEach for isolation
      - Quality Contribution: Enables test isolation
      - Worked Example: spawn(), signal(), reset() → all history empty
      */
      const handle = await manager.spawn({ command: 'echo' });
      await manager.signal(handle.pid, 'SIGINT');

      manager.reset();

      expect(manager.getSpawnHistory()).toHaveLength(0);
      expect(manager.getSignalsSent(handle.pid)).toHaveLength(0);
      expect(await manager.isRunning(handle.pid)).toBe(false);
    });
  });
});
