/**
 * MermaidRenderer - Client Component for rendering Mermaid diagrams
 *
 * Renders Mermaid diagram code as SVG elements with theme support.
 * Uses dynamic import() for lazy-loading (~1.5MB mermaid bundle).
 *
 * Features:
 * - Lazy loading: mermaid loaded only when diagram mounts
 * - Theme support: re-renders on light/dark theme change
 * - Error handling: graceful error display for invalid syntax
 * - Unique IDs: useId() prevents collision on multiple diagrams
 * - Async rendering: loading state during render
 *
 * Implements:
 * - AC-14: Mermaid to SVG rendering
 * - AC-16: Theme-aware diagrams
 * - AC-17: Error handling
 * - AC-18: Async/non-blocking rendering
 *
 * DYK Session Decisions:
 * - DYK #1: Custom component pattern (not rehype-mermaid)
 * - DYK #2: useId() for unique IDs
 * - DYK #3: Re-render on theme change (Mermaid limitation)
 * - DYK #4: svg state as implicit mount detection
 * - DYK #5: Dynamic import in useEffect (not next/dynamic)
 *
 * @see CodeBlock for the router that detects mermaid language
 */
'use client';

import { useTheme } from 'next-themes';
import { useEffect, useId, useRef, useState } from 'react';

import './mermaid-renderer.css';

export interface MermaidRendererProps {
  /** The raw Mermaid diagram code */
  code: string;
}

/**
 * MermaidRenderer component for rendering Mermaid diagrams as SVG.
 *
 * @example
 * <MermaidRenderer code={`flowchart TD
 *   A[Start] --> B[End]
 * `} />
 */
export function MermaidRenderer({ code }: MermaidRendererProps) {
  const ref = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { resolvedTheme } = useTheme();
  const uniqueId = useId();

  useEffect(() => {
    // Skip rendering if no code provided
    if (!code || !code.trim()) {
      setError('No diagram code provided');
      return;
    }

    let mounted = true;

    // Reset state on code/theme change
    setSvg(null);
    setError(null);

    // Lazy load mermaid (~1.5MB) only when diagram mounts
    import('mermaid')
      .then(async (mermaidModule) => {
        if (!mounted) return;
        const mermaid = mermaidModule.default;

        // Configure Mermaid with theme matching app theme
        // Note: Mermaid doesn't support CSS variables, requires re-render
        mermaid.initialize({
          startOnLoad: false,
          theme: resolvedTheme === 'dark' ? 'dark' : 'default',
          // Additional security: disable potentially dangerous features
          securityLevel: 'strict',
        });

        try {
          // Sanitize ID for Mermaid (replace colons from useId)
          const safeId = `mermaid-diagram${uniqueId.replace(/:/g, '-')}`;

          const result = await mermaid.render(safeId, code);

          if (mounted) {
            setSvg(result.svg);
            // Bind interactive functions if present (click handlers, etc.)
            if (result.bindFunctions && ref.current) {
              result.bindFunctions(ref.current);
            }
          }
        } catch (err) {
          if (mounted) {
            const message = err instanceof Error ? err.message : 'Unable to render diagram';
            setError(message);
          }
        }
      })
      .catch((err) => {
        if (mounted) {
          setError('Failed to load diagram renderer');
        }
      });

    return () => {
      mounted = false;
    };
  }, [code, resolvedTheme, uniqueId]);

  // Error state: show error message
  if (error) {
    return (
      <div className="mermaid-renderer mermaid-renderer-error" role="alert">
        <span className="mermaid-renderer-error-icon" aria-hidden="true">
          ⚠️
        </span>
        <span className="mermaid-renderer-error-text">Diagram error: {error}</span>
      </div>
    );
  }

  // Loading state: show placeholder (prevents hydration mismatch)
  if (!svg) {
    return (
      <div className="mermaid-renderer mermaid-renderer-loading" aria-busy="true">
        <span className="mermaid-renderer-loading-text">Loading diagram...</span>
      </div>
    );
  }

  // Success state: render SVG
  return (
    <div
      ref={ref}
      className="mermaid-renderer mermaid-renderer-svg"
      role="img"
      aria-label="Mermaid diagram"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by mermaid.render() which sanitizes input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
