import XCTest
@testable import streamd

/// Test: streamd JWT verifier + Origin gate vs the shared auth vectors (dossier T004, AC-9).
/// Behaviour: the `good` vector verifies; expired/wrong-aud/wrong-key are each rejected with
///   the matching reason; HKDF derivation matches Node byte-for-byte; the Origin gate enforces
///   the allowlist with the remote-view close codes (4401 E_AUTH / 4402 E_ORIGIN).
/// Boundary: expired exp, wrong audience, wrong signing key, missing/empty/`null` origin, missing token.
/// Determinism: reads the SAME test/contracts/remote-view-auth-vectors.json the TS side uses;
///   `now` is pinned so the expired vector is reliably in the past.
/// Oracle: remote-view-auth-vectors.json + signing-key.ts (HKDF) + terminal-auth.ts (Origin).
final class AuthVectorsTests: XCTestCase {

    /// Pinned clock: after expPast (1700000300) and before expFuture (4102444800).
    private let now: TimeInterval = 2_000_000_000

    private struct AuthVectorsFile: Decodable {
        let alg: String
        let issuer: String
        let audience: String
        let signingKeyHex: String
        let vectors: [Vector]
        struct Vector: Decodable {
            let name: String
            let valid: Bool
            let token: String
            let reason: String?
        }
    }

    private func loadVectors() throws -> AuthVectorsFile {
        try JSONDecoder().decode(AuthVectorsFile.self, from: Data(contentsOf: Fixtures.authVectors))
    }

    func testVectorMetadataMatchesContract() throws {
        let fx = try loadVectors()
        XCTAssertEqual(fx.alg, "HS256")
        XCTAssertEqual(fx.issuer, RemoteViewAuth.jwtIssuer)
        XCTAssertEqual(fx.audience, RemoteViewAuth.jwtAudience)
    }

    func testEveryVectorVerifiesAsExpected() throws {
        let fx = try loadVectors()
        let key = try XCTUnwrap(BinaryFrame.bytes(fromHex: fx.signingKeyHex))
        XCTAssertEqual(key.count, 32)
        for v in fx.vectors {
            let result = RemoteViewAuth.verifyJWT(v.token, key: key, now: now)
            switch result {
            case .success:
                XCTAssertTrue(v.valid, "vector '\(v.name)' verified but should be invalid (\(v.reason ?? ""))")
            case .failure(let err):
                XCTAssertFalse(v.valid, "vector '\(v.name)' rejected (\(err)) but should be valid")
            }
        }
    }

    func testRejectionReasonsAreSpecific() throws {
        let fx = try loadVectors()
        let key = try XCTUnwrap(BinaryFrame.bytes(fromHex: fx.signingKeyHex))
        func verdict(_ name: String) throws -> Result<RemoteViewAuth.JWTClaims, RemoteViewAuth.AuthError> {
            let token = try XCTUnwrap(fx.vectors.first { $0.name == name }).token
            return RemoteViewAuth.verifyJWT(token, key: key, now: now)
        }
        // good → claims with the expected subject
        if case .success(let claims) = try verdict("good") {
            XCTAssertEqual(claims.sub, "remote-user")
            XCTAssertEqual(claims.aud, RemoteViewAuth.jwtAudience)
        } else { XCTFail("good vector should verify") }
        // expired → .expired
        XCTAssertEqual(try verdict("expired").failureError, .expired)
        // wrong-aud → .wrongAudience (signature is valid, audience is not)
        XCTAssertEqual(try verdict("wrong-aud").failureError, .wrongAudience)
        // wrong-key → .badSignature (HMAC mismatch)
        XCTAssertEqual(try verdict("wrong-key").failureError, .badSignature)
    }

    func testMissingExpiryRejected() throws {
        // A token signed with the pinned vector key (000102…1f) but carrying NO `exp` claim.
        // The frozen route always mints exp(+300s); a no-exp token must be rejected, not
        // accepted forever (F005, HIGH — companion finding on Batch A).
        let fx = try loadVectors()
        let key = try XCTUnwrap(BinaryFrame.bytes(fromHex: fx.signingKeyHex))
        let noExp = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZW1vdGUtdXNlciIsImlzcyI6ImNoYWluZ2xhc3MiLCJhdWQiOiJyZW1vdGUtdmlldy13cyIsImlhdCI6MTcwMDAwMDAwMH0.XwEvtHt-TeWghH7VZi1rgYPFuv3WFXWlKVPsyVbF5uc"
        XCTAssertEqual(RemoteViewAuth.verifyJWT(noExp, key: key, now: now).failureError, .missingExpiry)
    }

    func testHkdfDerivationMatchesNodeByteForByte() {
        // Oracle generated by Node hkdfSync('sha256', code, salt, info, 32).
        let key = RemoteViewAuth.deriveSigningKey(fromCode: "test-bootstrap-code-123")
        XCTAssertEqual(BinaryFrame.hex(key),
                       "23b5e58be418840d5214b3b3a9ca2f4dbcd38cde689db5645c36d1b24e690273")
    }

    func testSigningKeyFromAuthSecretEnv() throws {
        let key = try RemoteViewAuth.signingKey(bootstrapPath: nil, env: ["AUTH_SECRET": "hunter2"])
        XCTAssertEqual(key, Array("hunter2".utf8))
    }

    func testSigningKeyFromBootstrapFile() throws {
        let dir = NSTemporaryDirectory()
        let path = (dir as NSString).appendingPathComponent("streamd-bootstrap-test.json")
        let json = #"{"version":1,"code":"test-bootstrap-code-123","createdAt":"x","rotatedAt":"y"}"#
        try json.write(toFile: path, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(atPath: path) }
        let key = try RemoteViewAuth.signingKey(bootstrapPath: path, env: [:])
        XCTAssertEqual(BinaryFrame.hex(key),
                       "23b5e58be418840d5214b3b3a9ca2f4dbcd38cde689db5645c36d1b24e690273")
    }

    // MARK: Origin allowlist

    func testParseAllowedOrigins() {
        XCTAssertNil(RemoteViewAuth.parseAllowedOrigins(nil))
        XCTAssertNil(RemoteViewAuth.parseAllowedOrigins("   "))
        XCTAssertEqual(RemoteViewAuth.parseAllowedOrigins("a, b ,,c"), Set(["a", "b", "c"]))
    }

    func testBuildDefaultAllowedOrigins() {
        let http = RemoteViewAuth.buildDefaultAllowedOrigins(port: "3000", httpsEnabled: false)
        XCTAssertTrue(http.contains("http://localhost:3000"))
        XCTAssertTrue(http.contains("http://127.0.0.1:3000"))
        XCTAssertFalse(http.contains("https://localhost:3000"))

        let https = RemoteViewAuth.buildDefaultAllowedOrigins(port: "3000", httpsEnabled: true)
        XCTAssertTrue(https.contains("https://localhost:3000"))
    }

    func testAuthorizeUpgradeScenarios() throws {
        let fx = try loadVectors()
        let key = try XCTUnwrap(BinaryFrame.bytes(fromHex: fx.signingKeyHex))
        let goodToken = try XCTUnwrap(fx.vectors.first { $0.name == "good" }).token
        let expiredToken = try XCTUnwrap(fx.vectors.first { $0.name == "expired" }).token
        let allowed: Set<String> = ["http://localhost:3000"]

        // happy path
        XCTAssertEqual(
            RemoteViewAuth.authorizeUpgrade(origin: "http://localhost:3000", token: goodToken,
                                            allowedOrigins: allowed, key: key, now: now),
            .ok(username: "remote-user"))

        // bad origin → 4402 E_ORIGIN
        if case let .rejected(code, ec, _) = RemoteViewAuth.authorizeUpgrade(
            origin: "http://evil.example", token: goodToken, allowedOrigins: allowed, key: key, now: now) {
            XCTAssertEqual(code, 4402); XCTAssertEqual(ec, .eOrigin)
        } else { XCTFail("bad origin should be rejected") }

        // origin null → 4402
        if case let .rejected(code, ec, _) = RemoteViewAuth.authorizeUpgrade(
            origin: "null", token: goodToken, allowedOrigins: allowed, key: key, now: now) {
            XCTAssertEqual(code, 4402); XCTAssertEqual(ec, .eOrigin)
        } else { XCTFail("null origin should be rejected") }

        // missing token → 4401 E_AUTH
        if case let .rejected(code, ec, _) = RemoteViewAuth.authorizeUpgrade(
            origin: "http://localhost:3000", token: nil, allowedOrigins: allowed, key: key, now: now) {
            XCTAssertEqual(code, 4401); XCTAssertEqual(ec, .eAuth)
        } else { XCTFail("missing token should be rejected") }

        // expired token (origin ok) → 4401 E_AUTH
        if case let .rejected(code, ec, _) = RemoteViewAuth.authorizeUpgrade(
            origin: "http://localhost:3000", token: expiredToken, allowedOrigins: allowed, key: key, now: now) {
            XCTAssertEqual(code, 4401); XCTAssertEqual(ec, .eAuth)
        } else { XCTFail("expired token should be rejected") }
    }
}

/// Small helper to pull the error out of a `Result` for assertions.
private extension Result {
    var failureError: Failure? {
        if case .failure(let e) = self { return e }
        return nil
    }
}
